log_level = "warn"
outputs = "All" 
position = "Top"

[modules]
left = [ [ "Workspaces" ] ]
center = [ [ "Clock", "Updates" ] ]
right = [ "SystemInfo", [  "Tray", "Privacy", "Settings" ] ]

[clock]
format =  "%A, %b %d – %T"

[updates]
check_cmd = "checkupdates; yay -Qua"
update_cmd = 'ghostty -e fish -c "if yay; echo ✅ Done! Press Enter to exit; else; echo ❌ yay failed! Press Enter to exit; end; read"'

[workspaces]
visibility_mode = "MonitorSpecific"
enable_workspace_filling = false

[settings]
lock_cmd = "playerctl --all-players pause; nixGL hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueberry"

[appearance]
scale_factor = 1.2
style = "Islands"
opacity = 0.75

primary_color = "#7aa2f7"
success_color = "#9ece6a"
text_color = "#a9b1d6"
workspace_colors = [ "#7aa2f7", "#9ece6a" ]
special_workspace_colors = [ "#7aa2f7", "#9ece6a" ]

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1a1b26"
weak = "#24273a"
strong = "#414868"

[appearance.secondary_color]
base = "#0c0d14"

